### ISSUE TITLE
[IOS] Cant type anything if locale is different to en_US

### ISSUE THREAD

**Issue by sclavijo93** [inKindCards/react-native-money#10]
Hello! I'm trying to change the locale to use the currency of my country but I found that if change the locale I can't type anything in the textinput

https://user-images.githubusercontent.com/19956031/149949641-13233f55-2323-4aac-8392-7a57fc3f1ebc.mov

EDIT:
I've tried with other locales:

| Locale | State |
| ---- | ----|
| es_AR | ✅  |
|es_BO| ✅ |
|es_CL| ❌ |
|es_CO| ✅ |
|es_CR| ✅ |
|es_DO| ✅ |
|es_ES| ✅ |
|es_PY| ❌ |
|pt_BR| ✅ |

It would be great if we could provide the preffix/suffix instead of choosing a locale to avoid this

**Comment by NathHorrigan** [comment]
Adding prefix, suffix and terminator support is definitely something we would like to do at some point but getting locales working perfectly is the main goal as it's the same interface and so if something doesn't work with a particular locale then it won't work with advanced config either.

Could you see if `es_CL` & `es_PY` works after trying this WIP branch:


```
npm i --save --force https://github.com/inKindCards/react-native-money#hotfix/non-fractional-currencies
```

**Comment by sclavijo93** [comment]
It works like a charm! 🔥 

https://user-images.githubusercontent.com/19956031/150375571-073a0b30-8731-444f-8c87-e4fb4d4b3bde.mov
